#!/bin/bash
#PBS -l nodes=1:ppn=8:dc2,walltime=0:08:00
#PBS -N crop_reorient
#PBS -V

if [ $ENV == "IUHPC" ]; then
   module load fsl
fi

rm -f t1.nii.gz

export input_t1=$(jq -r .t1 config.json)

cp $input_t1 t1.nii.gz

if [ $(jq -r .reorient config.json) == true ]; then
	fslreorient2std t1.nii.gz t1.nii.gz
fi

if [ $(jq -r .crop config.json) == true ]; then
	robustfov -i t1.nii.gz -r t1.nii.gz
fi


